### PR TITLE
Back to commonj

### PR DESCRIPTION
**Pull request by lep**
I wrote a script which can take a jass file without any docstrings and a jass.db which inserts all the matching docstrings to the un-annotated jass-file.
I then took a clean common.j and annotated it with a jass.db built from latest master commit. Then i deleted all the other jass files in this repo. That means we now only have the three original files in this repo†, that is common.j, common.ai and Blizzard.j.

Now here is my question: should we merge this? I know that some people were irritated by the way i organized/split up common.j, so that would be one reason to merge this.
Also this allows a much easier migration to a new common.j if we ever get a new one; just replace the annotated common.j with the one provided by blizzard and run the annotation script with the previously created jass.db

One downside of this approach is that the DB cannot be build incrementally and will always be recreated at whole but at least in CI i do that anyways (i think…).

@Luashine @WaterKnight any thoughts?

† and builtin-types.j

### CODE REVIEW

**Comment by Luashine** [comment]
I did get accustomed to the split files but I'm an odd one out because I've spent **so** much time both with vanilla and jassdoc. common.j is easier to navigate with ctrl+f, separate files require Find In Files or the like.

Eventually I'd like to add removed functions too (pretty crazy and also exclusively ROC Beta probably). What would the workflow look like there? Would it be possible to have a "common-rocbetav100.j" file with only those missing functions or must it be a complete file?

And if they are separate files, it'll mean some entries of the db are unreachable until you match a func signature in a .j file. What to do with unmatched entries? Flooding the console is one way, writing them to a temporary scratch file (when needed) is probably better?

EDIT: if the script can work on multiple files in one go, it'd export common.j+ai, blizzard.j, rocbeta.j - it'd mark all funcs as reachable because it has seen them at least once during export. End.

With categorized files right now these weird wishes of mine would be simply placed in a different file. Simply put, a one way conversion (.j -> db) does not raise these questions but leaves out updates.

With regards to the c-pyr-ght headache, the annotation of "user-provided" files is the right way to go. As if anybody cared :)

**Comment by lep** [comment]
> I did get accustomed to the split files but I'm an odd one out because I've spent **so** much time both with vanilla and jassdoc. common.j is easier to navigate with ctrl+f, separate files require Find In Files or the like.

I just use git grep or the web interface.

> Eventually I'd like to add removed functions too (pretty crazy and also exclusively ROC Beta probably). What would the workflow look like there? Would it be possible to have a "common-rocbetav100.j" file with only those missing functions or must it be a complete file?

Workflow would be just as it is now: if you don't want to put the beta stuff into the (then) common.j file just make another file.

> And if they are separate files, it'll mean some entries of the db are unreachable until you match a func signature in a .j file. What to do with unmatched entries? Flooding the console is one way, writing them to a temporary scratch file (when needed) is probably better?

There shouldn't be any "unreachable" stuff as the the DB was created from the stuff we have now and then (modulo bugs) the new common.j will have everything in it aswell, because it's the canonical common.j so there should be at least as many natives and stuff as in the split-up version.

> With categorized files right now these weird wishes of mine would be simply placed in a different file. Simply put, a one way conversion (.j -> db) does not raise these questions but leaves out updates.

As i said above, you can always create your weird files if you want ❤️ The database doesn't really care about the file organisation. It takes one or thousand jass files.
And we can also just *not* include files into the final DB if we want to.

**Comment by Luashine** [comment]
OK sounds great! I didn't have internet access when I wrote up the reply

> the web interface.

Its slower, now requires login and sometimes (definitely with big repos and for partial search) misses results. Just wanted to warn :)

**Comment by lep** [comment]
So if you're OK with this i would try it out. If we don't like this we can always (once i updated the annotate script) move back to old way or even think up a whole new way. And it's all in git anyways.

**Comment by Luashine** [comment]
Yes go ahead. I myself won't be able to try it out for a few weeks

**Pull request merged**
