### PR TITLE
Bite the bullet: Convert blizzard.j to LF (was mixed EOL)

### LINKED ISSUE #109: Change End-of-Line (EOL) for Blizzard.j
**Continuation of** https://github.com/lep/jassdoc/pull/108#issuecomment-1742047104 -- following [lep's last reply](https://github.com/lep/jassdoc/pull/108#issuecomment-1742876785) about it.

I'm typing this out below for my future self... it has wasted hours of my time already to grasp this :(

---

git blame points to this commit containing LF in the diffs: https://github.com/lep/jassdoc/commit/828d7ab1b12380cae0f9a1374048d0b56cd6e530 `828d7ab`.

I typed out the response yesterday but didn't have time to test so I didn't comment then. The only good article on this matter is `https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/` just skip the history part.

    git config --local core.autocrlf true
    git rm --cached -r .
    git reset --hard

The commands you typed out are really the only way to safely re-extract the files and apply new EOL rules. Use them for testing in the future. The only command I'd like to add is `git show <REVISION>:<FILE> > stdout.txt` to get the file as-is without conversions. WARNING though, you must NOT use CMD or Powershell else they may introduce LF->CRLF conversion on their own. For example:

1. `git show HEAD~1:Blizzard.j > prenormalized-Blz.j`
2. Do some conversion in new commit in either direction
3. `git show HEAD:Blizzard.j > postnormalized-Blz.j`
4. Observe that the internal representation in index has really changed by viewing these files.
5. Double-check with `git ls-files --eol`

Keep in mind, git's preferred internal representation for text is LF and only LF. The issue really is/was not that git automatically converts between LF/CRLF. It's that the file in working dir ended up having MIXED LF/CRLF, which git did not dare to convert to LF and thus checked in & committed MIXED into internal index.

The fact that git "did not dare" has to do with OS && autocrlf setting && writing LF in our case, when it had to be CRLF (as the rest of the file was CRLF already). You might've extracted the file as CRLF initially but then patched it with a tool in LF style.

In this context I regard `.gitconfig` as "what can I do with my setup to avoid having/introducing these issues" and `.gitattributes` as "what can the repository do with its settings to avoid issues" sort of a soft policy.

- gitconfig (not shared with repo)
   - [core.safecrlf](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresafecrlf) = true or warn -- setting to true will abort commits that would break line endings (aka mix LF and CRLF)
   - as an alternative to safecrlf, add your own pre-commit hooks.
   - [autocrlf](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreautocrlf), [answer on SO](https://stackoverflow.com/questions/3206843/how-line-ending-conversions-work-with-git-core-autocrlf-between-different-operat)
      - set to true if you're only gonna use Windows... what about in 3-5 years down the road?
         - _it's alright if you are not gonna dual-boot or share the git folder between Windows/*nix (uhh WSL anyone?)_
      - set to input otherwise (checked out into workdir as-is)
        - _Windows tooling could still write CRLF into LF files. But that's the lesser evil to fix, if it does not convert automatically (it should)._
      - set to false if you're gonna strictly specify all files through `.gitattributes` _(otherwise high chance of ending up with MIXED)_
- gitattributes (shared with repo)
   - `* text=auto eol=lf` -- for all files automatically detect if its binary/text (already default) but if it's text, git will respect our `eol` instead of `core.autocrlf`
      - this is per-file core.eol essentially. Git apparently ignores it if config `core.autocrlf` is == true/input

Back to the repo. Blizzard.j right now is in MIXED state internally with 98% CRLF and 2% LF. 

1. Fixing this to align with git's internal LF will mean a 14k line diff commit. Then we could force eol=lf on all files
2. Not doing anything (aka `text` is "unspecified") will continue to cause spurious merge conflicts and line conversions depending on user's core.autocrlf, especially dual-booting.
3. *Unsetting* text with `-text` will instruct git to not touch the lines anymore. We would live on with mixed lines. Doesn't seem too bad on the surface, but software would get confused and line replacements will pop up from time to time.
   - However it's possible to turn all internal index from MIXED (98% CRLF) into 100% CRLF with a small diff. This would give us a consistent file but *very unusual* for git. This is normally reserved for the likes of .BAT that require CRLF. Anyway the rest of the repo is LF, this would be odd too.
   - On the other hand this setting **encourages** mixing newlines in the future, it's inevitable someone will write LF from Unix world into this windowsy file.

Let's take Notepad++ for example. I've noticed it before, it will autodetect EOL based on the few lines in the beginning and only choose and only show one type of EOL (even if file is mixed). It sees Blizzard.j as CRLF (in reality MIXED).

1. Theorematis\[CRLF\]
2. arithmetici\[LF\]
3. demonstratio\[LF\]
6. nova.\[CRLF\]

---

Pressing ENTER after "arithmetici" and continuing to write will turn into:

1. Theorematis\[CRLF\]
2. arithmetici\[CRLF\]
   1. Gauss\[LF\]
4. demonstratio\[LF\]
7. nova.\[CRLF\]

-> We just changed the EOL and moved LF onto the other line

---

Pressing DELETE after "arithmetici", but then changing mind and pressing ENTER will remove LF but write CRLF:

1. Theorematis\[CRLF\]
2. arithmetici\[CRLF\]
4. demonstratio\[LF\]
6. nova.\[CRLF\]

-> We just changed EOL (renormalizing the file one line at a time lol)

---

I suggest to say [fuck it](https://www.youtube.com/watch?v=ak16XxnJK0g), bite the bullet and normalize Blizzard.j to only contain LF as the other files do (huge commit). Then set eol=lf for all files. And if you enabled `safecrlf = true` for yourself in config it would shout at you with (and abort the `git add`):

> fatal: CRLF would be replaced by LF in creditsother.pld

here you tried to add a CRLF'ed .pld file while the attributes require LF on the input side. I think it's a good thing, you can convert on your own (dos2unix). With `safecrlf = warn` it would work as it says but give you a warning.

`.gitattributes`

```
# All game scripts are CRLF, but LF works fine and we already use it
# aka "text" is set, enabling EOL conversion the way we want it if not forbidden by safecrlf
*.j			text eol=lf
*.ai		text eol=lf
# Not yet included in repo but can go with LF for consistency?
*.pld		text eol=lf
*.wts		text eol=lf
```

Sorry about the wall of text, I'm not happy with all this work either but finally got to the root of it ❤

### PR DESCRIPTION
**Pull request by Luashine**
Closes #109 

Blizzard.j is currently 99% CRLF, 1% LF. The rest of the repo is 100% LF (or autocrlf-ed on Windows, depends how you view it). `git ls-files --eol` where `i` is the `index` aka internally saved data.

While researching, I found out Github has the lesser known `?w=1` option to pull request change comparison, with this on it **hides** whitespace changes. I will update this post with a w=1 link.

I strongly recommend to set this config option to not mix CRLF/LF in the future: `git config --local core.safecrlf true` it will simply abort `git add` until you fix the file.

The alternative is to keep the MIXED line-endings inside git, because mixed they will continue to stay mixed in the working dir and cause whiteline clashes down the line, bloating diffs. However manual merging is still easy with this: https://git-scm.com/book/en/v2/Git-Tools-Advanced-Merging and `git merge -Xignore-space-change whitespace`

The rest is explained in #109

### CODE REVIEW

**Comment by lep** [comment]
Thanks for you effort researching this. I meant to reply in the original issue but i guess life got in the way. I think i allready wrote somewhere that this seems fine to me; web interface still works, etc. so i'm just going ahead and merge this.
I guess the perl scripts use `\n` which should be the OS newline but especially with `core.safecrlf=true` it shouldn't be a problem.

**Comment by Luashine** [comment]
Yes on Windows when using Lua (which is as low-level as C gets) you must open files in "wb" binary mode else Windows will automatically convert LF to CRLF on output. The only scenario with git I can think of is dual-booting and sharing that folder etc.

**Comment by Slayer95** [comment]
Note: some scripts on the wild rely on downloading Blizzard.j / common.j from this repo for calculating maps hashes. For good or evil, this change broke them.

**Comment by Luashine** [comment]
The scripts in this repo aren't original per se anyway. I don't see an argument here? if i remember correctly, lep mixed it up soon after :P

I suppose, if I trust my own comment enough, you can force CRLF or use files from [jass-history repo](https://github.com/Luashine/jass-history/blob/master/.gitattributes).

**Comment by Slayer95** [comment]
It's not argument. It's just an observation since my jaws didn't catch the bullet. The jass-history repo also seems to be normalized to LF. Consumers of any of these repos for the purpose I mentioned must assume that the source files originally had perfect CRLF, so that transforming line-endings yields the correct bytes.

At least, as far as I know, common.j and blizzard.j, did have full CRLF for versions 1.24-1.28f, and 1.29c. Verification pending for other versions.

**Comment by Luashine** [comment]
> The jass-history repo also seems to be normalized to LF.

I had linked you the gitattributes file with the forced CRLF. Essentially, **git is not EOL [clean](https://en.wikipedia.org/wiki/8-bit_clean)**.

> for calculating maps hashes

does wc3 compute hash sums of .j files for verification  or whats the use case?

**Comment by Slayer95** [comment]
> > The jass-history repo also seems to be normalized to LF.
> 
> I had linked you the gitattributes file with the forced CRLF. Essentially, **git is not EOL [clean](https://en.wikipedia.org/wiki/8-bit_clean)**.

Indeed, ``git checkout`` is not EOL-clean. But https://raw.githubusercontent.com is totally EOL-clean, which is why it downloads with LF, as-commited.

> > for calculating maps hashes
> 
> does wc3 compute hash sums of .j files for verification or whats the use case?

Yes. Host bots must know the correct hashes of the resolved ``common.j`` and ``blizzard.j`` files, for each map they want to host. (*)

Anyway, just commenting for docs-purposes, since this entire repository is about documentation.

(*) It's a bit more complex than that. JASS files are actually concatenated and only then hashed.

**Comment by Slayer95** [comment]
> I had linked you the gitattributes file with the forced CRLF.

Oh, you *may* be under the impression that your repository actually fully respects that setting. Well, it doesn't:

```sh
$ wget https://raw.githubusercontent.com/Luashine/jass-history/refs/heads/master/war3extract/TFT-v1.27b-ru/Scripts/common.j
$ grep -cU $'\r' common.j
0
```

**Comment by Luashine** [comment]
> Indeed, git checkout is not EOL-clean.

You are right: `git show HEAD:./war3extract/Beta-ROC-v1.10/Scripts/common.j | xxd` - is committed as LF.

> Well, it doesn't: https://raw.githubusercontent.com/Luashine/jass-history/

Arguably a bug, that Github decided to not respect the gitattributes and probably use something similar to git show.

**Comment by Slayer95** [comment]
> Arguably a bug, that Github decided to not respect the gitattributes and probably use something similar to git show.

I don't think I have ever used ``eol=crlf`` (I generally prefer ``core.autocrlf input``, though that's certainly not the best setting for this issue). However, isn't ``eol=crlf`` literally ``"checkout Windows-style, commit Unix-style"``? If that's the case, then it's not a Git nor GitHub bug, just normal Git behavior.

If you are interested in these files getting commited as CRLF, I'd suggest setting ``-text`` in .gitattributes, so they are treated as binary. Diffing them cross-folders *might* then require: ``git diff --no-index --text v1/Scripts/common.j v2/Scripts/common.j``. Fingers-crossed whether that setting messes GitHub Web rendering.

That said, anything any of you may change is totally up to you. There are pros and cons anyways.

**Comment by Luashine** [comment]
No, no, this is a valid complaint. I expect renormalize to work:

>  Since Git 2.16 (Q1 2018) there is another way (other than deleting the index content), which is a new and safer way to record the fact that you are correcting the end-of-line convention:

> git add --renormalize . 

There's a reason I added this bizarre paragraph to the repo:

> The repository is cursed, expect commits to be rebased, petted, fed lead-contaminated nuts, removed, travel back in time... Magic is not for everyone. Consult your doctor before use.

> **Only tags are stable references.**

In the end I still believe, as part of "working with files", github raw should be behaving like checkout and respect the attributes and transformations as best as it can (without running program filters).

**Pull request merged**
