### PR TITLE
Notes for UI natives

### PR DESCRIPTION
**Pull request by Tasyen**

### CODE REVIEW

**Comment by lep** [comment]
Thank you very much. There are some stylistic choices which i wont bore you with. But two things:

1. Try to wrap (jass) code in backticks ```` `` ```` so that they will be autolinked in my jassbot site.

2. I see that you tagged a whole bunch of natives as `@async`. So far i have used that tag to annotate functions which may *return* different values for different players. You annotated functions which return nothing. So there is a little disconnect between the usage. Can you elaborate what exactly you meant when you annotated such a function?
I mean these ui functions are probably to be used in a `GetLocalPlayer()` block i assume? So they're async-safe? That is the notion which i use in my desync checker. Maybe i should transfer that.

**Comment by Tasyen** [comment]
I used @async when the function itself does not produce problems in GetLocalPlayer() block. But I will change it to your rule.

Does your bot parses the comments? I guess so. Because I only wrote comments with some jass code?

**Comment by lep** [comment]
The various perl and haskell scripts in this repo take all the .j-files 
and produce a sqlite database. I use this DB to power the documentation 
of my jassbot website. If you look
[here](https://lep.duckdns.org/app/jassbot/doc/Preloader) you can see 
how the comments for `Preloader` are displayed (you need JavaScript 
enabled). And you can see how all the Natives are highlighted and clickable.

**Comment by lep** [comment]
Merged. Thanks again. I will update the README but for just to write it here (and i only noticed it after building the DB with your changes): my parser wants the normal comment stuff first and then any tags.

**Comment by lep** [comment]
Thank you very much. There are some stylistic choices which i wont bore 
you with. But two things:

1. Try to wrap (jass) code in backticks ```` `` ```` so that they will 
be autolinked in my jassbot site.

2. I see that you tagged a whole bunch of natives as ***@***.***`. So far i 
have used that tag to annotate functions which may *return* different 
values for different players. You annotated functions which return 
nothing. So there is a little disconnect between the usage. Can you 
elaborate what exactly you meant when you annotated such a function?
I mean these ui functions are probably to be used in a 
`GetLocalPlayer()` block i assume? So they're async-safe? That is the 
notion which i use in my desync checker. Maybe i should transfer that.

**Pull request merged**
